name: BetterServer
version: 0.0.1-b
api-version: 1.19
author: jeabapLANG
main: Main
commands:
  alert:
    description: Envoie une alerte à tout les joueu(rs/ses)
    permission: alert.use

  spawn:
    description: Teleporte l(e/a) joueu(r/euse) au point d'apparition du serveur
    permission: spawn.use
  last:
    description: Teleporte l(e/a) joueu(r/euse) à sa dernière localisation avant un tp ou une mort
    permission: last.use
  msg:
    description: Envoie un message au joueur cible
    permission: msg.use