name: BetterServer
version: 0.0.1-b
api-version: 1.19
author: jeabapLANG
main: src.com.github.jeabaplang.betterserver.Main
commands:
  alert:
    description: Envoie une alerte à tout les joueu(rs/ses)
    usage: /<command> [message]
    permission: alert.use
  giveeditor:
    description: Donne au joueu(r/euse) un item permettant d'editer le monde
    permission: giveeditor.use
    usage: /<command>

  spawn:
    description: Teleporte l(e/a) joueu(r/euse) au point d'apparition du serveur
    permission: spawn.use
    usage: /<command>
  last:
    description: Teleporte l(e/a) joueu(r/euse) à sa dernière localisation avant un tp ou une mort
    permission: last.use
    usage: /<command>